global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['127.0.0.1:8429']
  # - job_name: 'vmalert'
  #   static_configs:
  #     - targets: ['127.0.0.1:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['127.0.0.1:8428']
